### ISSUE TITLE
Microsoft Logo to My Company logo

### ISSUE THREAD

**Issue by AkashPatel136** [misskristine94/ColourfulLoader#1]
@misskristine94 How can I change Microsoft Logo to My Company Logo in SVG code?

**Comment by kristinekolodziejski** [comment]
Hi @AkashPatel136, thank you for your comment! There are some additional steps to add your company logo as you have to manipulate the SVG code - based on your question, I have now recorded a YouTube video which will be going live on my channel tomorrow at 5pm BST time - here's the link to my channel :) https://www.youtube.com/c/KristineKolodziejski/videos
